name: pytest
on: workflow_dispatch

jobs:
  pytest:
    runs-on: unbuntu-latest
    steps:
      - name: clone repository
        run: |
          pwd
          git clone git@github.com:gracezhang2024/github-actions-python.git
          cd github-actions-python
          pwd
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest